---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: summit-embargo-metrics
  labels:
    app: metrics
    site: summit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics
      site: summit
  template:
    metadata:
      labels:
        app: metrics
        site: summit
    spec:
      containers:
      - name: metrics
        image: "ghcr.io/lsst-dm/embargo-butler-ingest:prod"
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis
              key: redis-password
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
