---
apiVersion: v1
kind: Service
metadata:
  name: oga-butler-redis
  labels:
    app: redis
  annotations:
    metallb.universe.tf/address-pool: sdf-services
spec:
  type: LoadBalancer
  internalTrafficPolicy: Cluster
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-volume
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oga-butler-redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: "docker.io/redis:7.0.8"
        command:
        - redis-server
        - '--appendonly'
        - 'yes'
        - '--requirepass'
        - $(REDIS_PASSWORD)
        env:
        - name: MASTER
          value: "true"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: redis-password
              name: redis
        resources:
          requests:
            cpu: 100m
            memory: 1Gi
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: redis-volume
